#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

hooksdir="$(dirname "${0}")/$(basename "${0}").d"
if [ -d "${hooksdir}" ] ; then
    find "${hooksdir}" -type f -executable | while read hook ; do
        env against="${against}" "${hook}" || exit $?
    done
fi
